name: habit_app
description: "Habit tracker app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: 2.0.17
  shimmer: ^3.0.0
  custom_refresh_indicator: ^4.0.1
  pull_to_refresh: ^2.0.0
  swipeable_page_route: ^0.4.7
  mask_text_input_formatter: ^2.9.0
  toastification: ^2.3.0

  # State management
  flutter_bloc: ^9.0.0
  provider: ^6.1.4

  # Navigation
  go_router: ^15.0.0

  # Dependency injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Data modeling and serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  equatable: ^2.0.7

  # Utils
  dartz: ^0.10.1
  faker: ^2.2.0

  # Testing
  mocktail: ^1.0.4

  # Logging
  talker_flutter: ^4.8.0
  talker_bloc_logger: ^4.8.0

  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

  #some
  mime: ^2.0.0
  path: ^1.9.1
  dio: ^5.8.0+1
  talker_dio_logger: ^4.8.3
  dots_indicator: ^4.0.1
  page_view_dot_indicator: ^2.3.0
  easy_date_timeline: ^2.0.9
  lottie: ^3.3.1
  flutter_heatmap_calendar: 
    path: packages/flutter_heatmap_calendar
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.15.1
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^15.2.9
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: null
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  bloc_test: ^10.0.0
  freezed: ^3.0.6
  bloc_lint: 0.2.0-dev.0
  drift_dev: ^2.26.1

flutter:
  uses-material-design: true

  assets:
    # - .env
    - lib/assets/icons/
    - lib/assets/illustrations/
    - lib/assets/animations/
    - lib/assets/pictures/
    - lib/assets/data/
    - lib/assets/screens/
    - lib/assets/app/
flutter_intl:
  enabled: true
