name: habit_app
description: "Habit tracker app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: 2.0.17
  shimmer: ^3.0.0
  custom_refresh_indicator: ^4.0.1
  pull_to_refresh: ^2.0.0
  swipeable_page_route: ^0.4.7
  mask_text_input_formatter: ^2.9.0
  toastification: ^2.3.0

  # State management
  flutter_bloc: ^9.0.0
  provider: ^6.1.4
  
  # Navigation
  go_router: ^15.0.0

  # Dependency injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Data modeling and serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  equatable: ^2.0.7

  # Backend and authentication
  supabase_flutter: ^2.8.4
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  flutter_dotenv: ^5.2.1

  # Utils
  dartz: ^0.10.1
  faker: ^2.2.0

  # Testing
  mocktail: ^1.0.4

  # Logging
  talker_flutter: ^4.8.0
  talker_bloc_logger: ^4.8.0
  mime: ^2.0.0
  path: ^1.9.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  dio: ^5.8.0+1
  talker_dio_logger: ^4.8.3
  flutter_secure_storage: ^4.2.1
  dots_indicator: ^4.0.1
  page_view_dot_indicator: ^2.3.0
  easy_date_timeline: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner: ^2.4.15  
  json_serializable: ^6.9.5
  bloc_test: ^10.0.0
  freezed: ^3.0.6
  bloc_lint: 0.2.0-dev.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/icons/
    - lib/assets/illustrations/

