// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzSTrpUfWqhcmpvJJ5pmyGxR9PmE3H9M',
    appId: '1:805590698825:web:056e6713da3ceb68d0a898',
    messagingSenderId: '805590698825',
    projectId: 'habit-app-8e36f',
    authDomain: 'habit-app-8e36f.firebaseapp.com',
    storageBucket: 'habit-app-8e36f.firebasestorage.app',
    measurementId: 'G-YZB0GHWJGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9JxfGsAu2TKmVtP7RQeDvQYXf66iQtVM',
    appId: '1:805590698825:android:80581e7f353adb50d0a898',
    messagingSenderId: '805590698825',
    projectId: 'habit-app-8e36f',
    storageBucket: 'habit-app-8e36f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_5NVFTr6HvxLzFt-i1WAmQcyKA0kg9kk',
    appId: '1:805590698825:ios:1c62ce39315d6ab1d0a898',
    messagingSenderId: '805590698825',
    projectId: 'habit-app-8e36f',
    storageBucket: 'habit-app-8e36f.firebasestorage.app',
    iosBundleId: 'com.bakberdi.adet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_5NVFTr6HvxLzFt-i1WAmQcyKA0kg9kk',
    appId: '1:805590698825:ios:1061731578e84542d0a898',
    messagingSenderId: '805590698825',
    projectId: 'habit-app-8e36f',
    storageBucket: 'habit-app-8e36f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHzSTrpUfWqhcmpvJJ5pmyGxR9PmE3H9M',
    appId: '1:805590698825:web:05e5ce4143244ed9d0a898',
    messagingSenderId: '805590698825',
    projectId: 'habit-app-8e36f',
    authDomain: 'habit-app-8e36f.firebaseapp.com',
    storageBucket: 'habit-app-8e36f.firebasestorage.app',
    measurementId: 'G-EP051YW8CL',
  );
}